// <auto-generated />
using System;
using ArtHistoryMap.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArtHistoryMap.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtHistoryMap.Api.Entities.ArtMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ArtMovements");
                });

            modelBuilder.Entity("ArtHistoryMap.Api.Entities.ArtMovementRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceMovementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetMovementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetMovementId");

                    b.HasIndex("SourceMovementId", "TargetMovementId", "RelationType")
                        .IsUnique();

                    b.ToTable("ArtMovementRelations");
                });

            modelBuilder.Entity("ArtHistoryMap.Api.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("ArtHistoryMap.Api.Entities.ArtistMovement", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid");

                    b.HasKey("ArtistId", "MovementId");

                    b.HasIndex("MovementId");

                    b.ToTable("ArtistMovements");
                });

            modelBuilder.Entity("ArtHistoryMap.Api.Entities.Artwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("ArtHistoryMap.Api.Entities.ArtMovementRelation", b =>
                {
                    b.HasOne("ArtHistoryMap.Api.Entities.ArtMovement", "SourceMovement")
                        .WithMany("OutgoingRelations")
                        .HasForeignKey("SourceMovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtHistoryMap.Api.Entities.ArtMovement", "TargetMovement")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("TargetMovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceMovement");

                    b.Navigation("TargetMovement");
                });

            modelBuilder.Entity("ArtHistoryMap.Api.Entities.ArtistMovement", b =>
                {
                    b.HasOne("ArtHistoryMap.Api.Entities.Artist", "Artist")
                        .WithMany("ArtistMovements")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtHistoryMap.Api.Entities.ArtMovement", "Movement")
                        .WithMany("ArtistMovements")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("ArtHistoryMap.Api.Entities.Artwork", b =>
                {
                    b.HasOne("ArtHistoryMap.Api.Entities.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("ArtHistoryMap.Api.Entities.ArtMovement", b =>
                {
                    b.Navigation("ArtistMovements");

                    b.Navigation("IncomingRelations");

                    b.Navigation("OutgoingRelations");
                });

            modelBuilder.Entity("ArtHistoryMap.Api.Entities.Artist", b =>
                {
                    b.Navigation("ArtistMovements");

                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
